// Mock categories
export const categories = [
  { id: "clothing", name: "Clothing", count: 42 },
  { id: "electronics", name: "Electronics", count: 38 },
  { id: "home", name: "Home & Kitchen", count: 24 },
  { id: "accessories", name: "Accessories", count: 31 },
  { id: "footwear", name: "Footwear", count: 19 },
  { id: "beauty", name: "Beauty & Personal Care", count: 27 },
  { id: "sports", name: "Sports & Outdoors", count: 15 },
]

// Mock brands
export const brands = [
  { id: "brand1", name: "TechGear", count: 18 },
  { id: "brand2", name: "FashionHub", count: 24 },
  { id: "brand3", name: "HomeStyle", count: 12 },
  { id: "brand4", name: "SportsPro", count: 9 },
  { id: "brand5", name: "BeautyEssentials", count: 15 },
]

// Sort options
export const sortOptions = [
  { value: "featured", label: "Featured" },
  { value: "newest", label: "Newest Arrivals" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "best-selling", label: "Best Selling" },
  { value: "rating", label: "Top Rated" },
]

// Mock product data
export const allProducts = [
  {
    id: 1,
    name: "Premium T-Shirt",
    price: 29.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "clothing",
    brand: "FashionHub",
    rating: 4.5,
    isNew: true,
    isBestSeller: false,
    dateAdded: "2023-05-15",
  },
  {
    id: 2,
    name: "Wireless Headphones",
    price: 129.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "electronics",
    brand: "TechGear",
    rating: 4.2,
    isNew: false,
    isBestSeller: true,
    dateAdded: "2023-04-10",
  },
  {
    id: 3,
    name: "Leather Wallet",
    price: 49.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "accessories",
    brand: "FashionHub",
    rating: 4.0,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-03-22",
  },
  {
    id: 4,
    name: "Smart Watch",
    price: 199.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    category: "electronics",
    brand: "TechGear",
    rating: 4.7,
    isNew: true,
    isBestSeller: true,
    dateAdded: "2023-06-01",
  },
  {
    id: 5,
    name: "Running Shoes",
    price: 89.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "footwear",
    brand: "SportsPro",
    rating: 4.3,
    isNew: false,
    isBestSeller: true,
    dateAdded: "2023-02-15",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    price: 79.99,
    discount: 20,
    image: "/placeholder.svg?height=400&width=400",
    category: "electronics",
    brand: "TechGear",
    rating: 4.1,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-01-30",
  },
  {
    id: 7,
    name: "Backpack",
    price: 59.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "accessories",
    brand: "SportsPro",
    rating: 4.4,
    isNew: true,
    isBestSeller: false,
    dateAdded: "2023-05-05",
  },
  {
    id: 8,
    name: "Sunglasses",
    price: 39.99,
    discount: 5,
    image: "/placeholder.svg?height=400&width=400",
    category: "accessories",
    brand: "FashionHub",
    rating: 3.9,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-03-10",
  },
  {
    id: 9,
    name: "Coffee Maker",
    price: 149.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "home",
    brand: "HomeStyle",
    rating: 4.6,
    isNew: false,
    isBestSeller: true,
    dateAdded: "2023-02-20",
  },
  {
    id: 10,
    name: "Yoga Mat",
    price: 29.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "sports",
    brand: "SportsPro",
    rating: 4.2,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-04-15",
  },
  {
    id: 11,
    name: "Water Bottle",
    price: 19.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "sports",
    brand: "SportsPro",
    rating: 4.0,
    isNew: true,
    isBestSeller: false,
    dateAdded: "2023-05-25",
  },
  {
    id: 12,
    name: "Desk Lamp",
    price: 49.99,
    discount: 10,
    image: "/placeholder.svg?height=400&width=400",
    category: "home",
    brand: "HomeStyle",
    rating: 4.3,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-03-05",
  },
  {
    id: 13,
    name: "Moisturizer",
    price: 24.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "beauty",
    brand: "BeautyEssentials",
    rating: 4.5,
    isNew: false,
    isBestSeller: true,
    dateAdded: "2023-04-20",
  },
  {
    id: 14,
    name: "Wireless Mouse",
    price: 34.99,
    discount: 5,
    image: "/placeholder.svg?height=400&width=400",
    category: "electronics",
    brand: "TechGear",
    rating: 4.2,
    isNew: false,
    isBestSeller: false,
    dateAdded: "2023-02-10",
  },
  {
    id: 15,
    name: "Dress Shirt",
    price: 59.99,
    discount: 15,
    image: "/placeholder.svg?height=400&width=400",
    category: "clothing",
    brand: "FashionHub",
    rating: 4.1,
    isNew: false,
    isBestSeller: true,
    dateAdded: "2023-01-15",
  },
  {
    id: 16,
    name: "Facial Cleanser",
    price: 19.99,
    discount: 0,
    image: "/placeholder.svg?height=400&width=400",
    category: "beauty",
    brand: "BeautyEssentials",
    rating: 4.4,
    isNew: true,
    isBestSeller: false,
    dateAdded: "2023-06-05",
  },
]

export type Product = (typeof allProducts)[0]
export type Category = (typeof categories)[0]
export type Brand = (typeof brands)[0]
